spring.application.name=job-portal-system

# ENVIRONMENT MODE
spring.mode=${SPRING_MODE}

# ENV IMPORT
spring.config.import=file:.env[.properties]

# BASE URL
server.servlet.context-path=${BASE_URL}

# DATABASE
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

# HIBERNATE
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

# JWT
spring.jwt.secret=${JWT_SECRET}
spring.jwt.expiration=${JWT_EXPIRATION}

# MAIL SENDER
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
