spring.application.name=job-portal-system

# ENV IMPORT
spring.config.import=file:.env[.properties]

# BASE URL
server.servlet.context-path=${BASE_URL}

# DATABASE
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

# HIBERNATE
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update